framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: "sync://"
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            failed: "%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed"

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            'App\Message\SendAdminNotification': async
            'App\Message\AddPointsToUsers': async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
